# -*- coding: utf-8 -*-
"""Oops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGse2D-U9NYJQ09mjbKeWYyRo0-JQHxU
"""

class Vehicle:
    def __init__(self, name, rent):
        self.name = name
        self.rent = rent
        self.available = True

    def rent_vehicle(self, days, driver=False, petrol=False):
        if not self.available:
            print(f"\n {self.name} is not available!")
            return

        total_rent = self.rent * days
        if driver:
            total_rent += 500 * days
        if petrol:
            total_rent += 200 * days

        self.available = False
        print(f"\n {self.name} rented for {days} days.")
        print(f"Total Rent: ₹{total_rent}")

    def return_vehicle(self):
        if self.available:
            print(f"\n {self.name} is already available!")
        else:
            self.available = True
            print(f"\n {self.name} returned successfully!")


cars = [Vehicle("Innova", 3000), Vehicle("Swift", 1500)]
bikes = [Vehicle("R15", 800), Vehicle("CB Shine", 600)]

while True:
    print("\n===== Vehicle Rental System =====")
    print("1. View Cars  2. View Bikes  3. Rent Car  4. Rent Bike  5. Return Vehicle  6. Exit")
    choice = input("Enter choice: ")

    if choice == "1":
        print("\nAvailable Cars:")
        for i, car in enumerate(cars):
            status = "Available" if car.available else "Rented"
            print(f"{i+1}. {car.name} | ₹{car.rent}/day | {status}")

    elif choice == "2":
        print("\nAvailable Bikes:")
        for i, bike in enumerate(bikes):
            status = "Available" if bike.available else "Rented"
            print(f"{i+1}. {bike.name} | ₹{bike.rent}/day | {status}")

    elif choice == "3":
        for i, car in enumerate(cars):
            print(f"{i+1}. {car.name} | ₹{car.rent}/day")
        n = int(input("Enter car number: ")) - 1
        days = int(input("Enter number of days: "))
        driver = input("Need driver? (y/n): ").lower() == "y"
        petrol = input("Include petrol? (y/n): ").lower() == "y"
        cars[n].rent_vehicle(days, driver, petrol)

    elif choice == "4":
        for i, bike in enumerate(bikes):
            print(f"{i+1}. {bike.name} | ₹{bike.rent}/day")
        n = int(input("Enter bike number: ")) - 1
        days = int(input("Enter number of days: "))
        driver = input("Need driver? (y/n): ").lower() == "y"
        petrol = input("Include petrol? (y/n): ").lower() == "y"
        bikes[n].rent_vehicle(days, driver, petrol)

    elif choice == "5":
        all_vehicles = cars + bikes
        for i, v in enumerate(all_vehicles):
            status = "Available" if v.available else "Rented"
            print(f"{i+1}. {v.name} | {status}")
        n = int(input("Enter vehicle number to return: ")) - 1
        all_vehicles[n].return_vehicle()

    elif choice == "6":
        print("Thank you for using the system!")
        break

    else:
        print("Invalid choice!")